language: r
sudo: false

# Using the package cache to store R package dependencies can significantly
# speed up build times and is recommended for most builds.
cache: packages

os:
  #- windows
  - linux
  - osx
  
r:
  - release
  - devel


warnings_are_errors: true

r_packages:
  - covr
  
# before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
# deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true
  
after_success:
  - Rscript -e 'library(covr); codecov()'
#  - Rscript -e 'devtools::install();lintr::lint_package()'
